project:
  type: website

website:
  title: "Haley McCann"
  navbar:
    left:
      - text: "HM"
        href: index.qmd
    right:
      - text: "Home"
        href: index.qmd
      - text: "Portfolio"
        href: portfolio.qmd

format:
  html:
    css: style.css
